env:
  global:
    - TERM=dumb
    - GH_URI=https://github.com/gsson/katydid
    - secure: "b+n7e5iWYzP91Hn18gH/TjrhgdPwsi4NRryQrSCE2Utcf6LtVx4pOQjwnuFRGIHn2Qr2Bd0RXz1yJm5i3+HlUeOTixPSTLP3mjqXzoPQGtgyoyPnCRyyGVtS4tjVNkTY1iAWiXBwcvU+jnlZOcP2u4pQxLO1qrK6Z0y/jy2PUmM="

language: java

script: gradle -Djava.awt.headless=true clean check
after_success: gradle -Djava.awt.headless=true publishGhPages

branches:
  only:
    - travis

cache:
  directories:
  - .gradle
